/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tomaudothi;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thuan
 */
public class NgauNhien extends javax.swing.JFrame {

    /**
     * Creates new form NgauNhien
     */
    public NgauNhien() {
        initComponents();
    }
    
    Graph G = new Graph();
    public int n,m;
    ToMau tomau = new ToMau();
    String ketquaThamLam = new String();
    String ketquaWP = new String();
    private int i, s;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thamLamLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        thamLamArea = new javax.swing.JTextArea();
        wpLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wpArea = new javax.swing.JTextArea();
        troLaiButton = new javax.swing.JButton();
        soCungTextField = new javax.swing.JTextField();
        soDinhLabel = new javax.swing.JLabel();
        nhapButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTranArea = new javax.swing.JTextArea();
        toMauButton = new javax.swing.JButton();
        soCungLabel = new javax.swing.JLabel();
        soDinhTextField = new javax.swing.JTextField();
        tieuDeLabel = new javax.swing.JLabel();
        maTranLabel = new javax.swing.JLabel();
        xuatFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tô Màu Đồ Thị");

        thamLamLable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        thamLamLable.setText("Kết quả thuật toán tham lam");

        thamLamArea.setColumns(20);
        thamLamArea.setRows(5);
        jScrollPane2.setViewportView(thamLamArea);

        wpLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        wpLabel.setText("Kết quả thuật toán Whelsh Powell");

        wpArea.setColumns(20);
        wpArea.setRows(5);
        jScrollPane3.setViewportView(wpArea);

        troLaiButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        troLaiButton.setText("Trở lại");
        troLaiButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        troLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troLaiButtonActionPerformed(evt);
            }
        });

        soDinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soDinhLabel.setText("Nhập số đỉnh");

        nhapButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nhapButton.setText("Tạo đồ thị");
        nhapButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        nhapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapButtonActionPerformed(evt);
            }
        });

        maTranArea.setColumns(20);
        maTranArea.setRows(5);
        jScrollPane1.setViewportView(maTranArea);

        toMauButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        toMauButton.setText("Tô màu");
        toMauButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        toMauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMauButtonActionPerformed(evt);
            }
        });

        soCungLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soCungLabel.setText("Nhập số cung");

        tieuDeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tieuDeLabel.setText("SINH ĐỒ THỊ NGẪU NHIÊN ");

        maTranLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        maTranLabel.setText("Ma trận của đồ thị vừa nhập");

        xuatFileButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        xuatFileButton.setText("Xuất File");
        xuatFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        xuatFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(troLaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(tieuDeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(soCungLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soDinhLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soCungTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soDinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toMauButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xuatFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nhapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(maTranLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thamLamLable, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(wpLabel)))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(thamLamLable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(xuatFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(troLaiButton)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soDinhLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(soDinhTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soCungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(soCungTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addComponent(nhapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(maTranLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toMauButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapButtonActionPerformed
        s = 0;
        n = Integer.parseInt(soDinhTextField.getText()) ;
        for(i = 1; i <= n-1; i++){
            s+=i;
        }        
        m = Integer.parseInt(soCungTextField.getText()) ;

        if ( n*m <= 0) {
            JOptionPane.showMessageDialog(this, "Nhập số đỉnh và cung lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else if(s < m){
            JOptionPane.showMessageDialog(this, n + " đỉnh có tối đa " + s + " cung", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                ketquaThamLam = tomau.run(G, n, m);
                ketquaWP = tomau.run_wp(G, n, m);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NgauNhien.class.getName()).log(Level.SEVERE, null, ex);
            }
            maTranArea.setText(G.in(G)); 
        }      

    }//GEN-LAST:event_nhapButtonActionPerformed

    private void toMauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMauButtonActionPerformed
        wpArea.setText(ketquaWP);
        thamLamArea.setText(ketquaThamLam);
        System.out.println(G.in(G));
    }//GEN-LAST:event_toMauButtonActionPerformed

    private void troLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troLaiButtonActionPerformed
        TrangChu tc = new TrangChu();
        tc.setVisible(true);
        tc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_troLaiButtonActionPerformed

    private void xuatFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatFileButtonActionPerformed
        String tenFile = JOptionPane.showInputDialog(this, "Nhập tên file", "Xuất file", JOptionPane.DEFAULT_OPTION);
        File file = new File(tenFile);
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw.println(G.getN() + " " + G.getM());
        pw.print(maTranArea.getText());
        pw.println("Thuat toan tham lam");
        pw.println(ketquaThamLam);
        pw.println("Thuat toan Whelsh Powell");
        pw.println(ketquaWP);
        pw.close();
        JOptionPane.showConfirmDialog(this, "Lưu file hành công", "Thành công", JOptionPane.CLOSED_OPTION);

    }//GEN-LAST:event_xuatFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NgauNhien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NgauNhien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NgauNhien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NgauNhien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NgauNhien nn = new NgauNhien();
                nn.setVisible(true);
                nn.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea maTranArea;
    private javax.swing.JLabel maTranLabel;
    private javax.swing.JButton nhapButton;
    private javax.swing.JLabel soCungLabel;
    private javax.swing.JTextField soCungTextField;
    private javax.swing.JLabel soDinhLabel;
    private javax.swing.JTextField soDinhTextField;
    private javax.swing.JTextArea thamLamArea;
    private javax.swing.JLabel thamLamLable;
    private javax.swing.JLabel tieuDeLabel;
    private javax.swing.JButton toMauButton;
    private javax.swing.JButton troLaiButton;
    private javax.swing.JTextArea wpArea;
    private javax.swing.JLabel wpLabel;
    private javax.swing.JButton xuatFileButton;
    // End of variables declaration//GEN-END:variables
}
