/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tomaudothi;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Thuan
 */
public class NhapFile extends javax.swing.JFrame {

    /**
     * Creates new form NhapFile
     */
    public NhapFile() {
        initComponents();
    }
    Graph G = new Graph();
    ToMau tomau = new ToMau();
    String tenFile = new String();
    String ketquaThamLam = new String();
    String ketquaWP = new String();
    File F ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        maTranArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        thamLamArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        wpArea = new javax.swing.JTextArea();
        thamLamLable = new javax.swing.JLabel();
        wpLabel = new javax.swing.JLabel();
        maTranLabel = new javax.swing.JLabel();
        toMauButton = new javax.swing.JButton();
        troLaiButton = new javax.swing.JButton();
        tieuDeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        xuatFileButton = new javax.swing.JButton();
        ghiKQ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tô Màu Đồ Thị");

        maTranArea.setColumns(20);
        maTranArea.setRows(5);
        jScrollPane1.setViewportView(maTranArea);

        thamLamArea.setColumns(20);
        thamLamArea.setRows(5);
        jScrollPane2.setViewportView(thamLamArea);

        wpArea.setColumns(20);
        wpArea.setRows(5);
        jScrollPane3.setViewportView(wpArea);

        thamLamLable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        thamLamLable.setText("Kết quả thuật toán tham lam");

        wpLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        wpLabel.setText("Kết quả thuật toán Whelsh Powell");

        maTranLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        maTranLabel.setText("Ma trận của đồ thị vừa nhập");

        toMauButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        toMauButton.setText("Tô màu");
        toMauButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        toMauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMauButtonActionPerformed(evt);
            }
        });

        troLaiButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        troLaiButton.setText("Trở lại");
        troLaiButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        troLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troLaiButtonActionPerformed(evt);
            }
        });

        tieuDeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tieuDeLabel.setText("NHẬP ĐỒ THỊ TỪ FILE");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Lưu ý: Đảm bảo file đồ thị ");
        jLabel1.setAutoscrolls(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("chỉ nhận dạng file .txt");

        fileButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fileButton.setText("Chọn File");
        fileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("File vừa chọn ");

        xuatFileButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        xuatFileButton.setText("Xuất File");
        xuatFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        xuatFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatFileButtonActionPerformed(evt);
            }
        });

        ghiKQ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ghiKQ.setText("Ghi kết quả vào file đồ thị");
        ghiKQ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        ghiKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghiKQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(troLaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2)))
                            .addGap(25, 25, 25))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(tieuDeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(toMauButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ghiKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(xuatFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maTranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(73, 73, 73)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thamLamLable)
                                    .addComponent(wpLabel))))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tieuDeLabel)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(troLaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maTranLabel)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toMauButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ghiKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xuatFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(thamLamLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(wpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toMauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMauButtonActionPerformed
        wpArea.setText(ketquaWP);
        thamLamArea.setText(ketquaThamLam);
    }//GEN-LAST:event_toMauButtonActionPerformed

    private void troLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troLaiButtonActionPerformed
        TrangChu tc = new TrangChu();
        tc.setVisible(true);
        tc.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_troLaiButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter txtFilter = new FileNameExtensionFilter("txt", "txt");
        fileChooser.setFileFilter(txtFilter);
        fileChooser.setMultiSelectionEnabled(false);
        
        int x = fileChooser.showDialog(this, "OK");
        if(x == JFileChooser.APPROVE_OPTION){
            F = fileChooser.getSelectedFile();
            fileTextField.setText( F.getName());
            tomau = new ToMau(G);
            try {
                ketquaThamLam = tomau.run(G, F);
                ketquaWP = tomau.run_wp(G, F);
                if(ketquaThamLam == "")
                    JOptionPane.showConfirmDialog(this, "Không tìm được file", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
            }
            maTranArea.setText(G.in(G));
        }
    }//GEN-LAST:event_fileButtonActionPerformed

    private void xuatFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatFileButtonActionPerformed
        String tenFile = JOptionPane.showInputDialog(this, "Nhập tên file", "Xuất file", JOptionPane.DEFAULT_OPTION);
        File file = new File(tenFile);
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw.println(G.getN() + " " + G.getM());
        pw.print(maTranArea.getText());
        pw.println("Thuat toan tham lam");
        pw.println(ketquaThamLam);
        pw.println("Thuat toan Whelsh Powell");
        pw.println(ketquaWP);
        pw.close();
        JOptionPane.showConfirmDialog(this, "Lưu file hành công", "Thành công", JOptionPane.CLOSED_OPTION);
    }//GEN-LAST:event_xuatFileButtonActionPerformed

    private void ghiKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghiKQActionPerformed

        PrintWriter pw = null;
        try {
            pw = new PrintWriter(F);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NhapFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw.println(G.getN() + " " + G.getM());
        pw.print(maTranArea.getText());
        pw.println("Thuat toan tham lam");
        pw.println(ketquaThamLam);
        pw.println("Thuat toan Whelsh Powell");
        pw.println(ketquaWP);
        pw.close();
        JOptionPane.showConfirmDialog(this, "Lưu file hành công", "Thành công", JOptionPane.CLOSED_OPTION);

    }//GEN-LAST:event_ghiKQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhapFile nf = new NhapFile();
                nf.setVisible(true);
                nf.setLocationRelativeTo(null);            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileButton;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JButton ghiKQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea maTranArea;
    private javax.swing.JLabel maTranLabel;
    private javax.swing.JTextArea thamLamArea;
    private javax.swing.JLabel thamLamLable;
    private javax.swing.JLabel tieuDeLabel;
    private javax.swing.JButton toMauButton;
    private javax.swing.JButton troLaiButton;
    private javax.swing.JTextArea wpArea;
    private javax.swing.JLabel wpLabel;
    private javax.swing.JButton xuatFileButton;
    // End of variables declaration//GEN-END:variables
}


