/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tomaudothi;

/**
 *
 * @author Thuan
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tieuDeLabel = new javax.swing.JLabel();
        nhapFileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nhapCungButton = new javax.swing.JButton();
        ngauNhienButton = new javax.swing.JButton();
        huongDanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tô Màu Đồ Thị");
        setIconImages(null);

        tieuDeLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tieuDeLabel.setText("                                                   TÔ MÀU ĐỒ THỊ");
        tieuDeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        nhapFileButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nhapFileButton.setText("Nhập đồ thị từ File");
        nhapFileButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        nhapFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapFileButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomaudothi/anh/dothi1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(245, 144, 0)));

        nhapCungButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nhapCungButton.setText("Nhập đồ thị từ danh sách cung");
        nhapCungButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        nhapCungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapCungButtonActionPerformed(evt);
            }
        });

        ngauNhienButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ngauNhienButton.setText("Sinh đồ thị ngẫu nhiên");
        ngauNhienButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        ngauNhienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngauNhienButtonActionPerformed(evt);
            }
        });

        huongDanButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        huongDanButton.setText("?Hướng dẫn?");
        huongDanButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        huongDanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huongDanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(nhapFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(nhapCungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(ngauNhienButton, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(86, 86, 86))
            .addComponent(tieuDeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(huongDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieuDeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapCungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngauNhienButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(huongDanButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhapFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapFileButtonActionPerformed
        NhapFile nf = new NhapFile();
        nf.setVisible(true);
        nf.setLocationRelativeTo(null);  
        this.dispose();     
    }//GEN-LAST:event_nhapFileButtonActionPerformed

    private void nhapCungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapCungButtonActionPerformed
        NhapCung nc = new NhapCung();
        nc.setVisible(true);
        nc.setLocationRelativeTo(null);
        this.dispose();     
    }//GEN-LAST:event_nhapCungButtonActionPerformed

    private void ngauNhienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngauNhienButtonActionPerformed
        NgauNhien nn = new NgauNhien();
        nn.setVisible(true);
        nn.setLocationRelativeTo(null);
        this.dispose();     
    }//GEN-LAST:event_ngauNhienButtonActionPerformed

    private void huongDanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huongDanButtonActionPerformed
        HuongDan hd = new HuongDan();
        hd.setVisible(true);
        hd.setLocationRelativeTo(null);
        this.dispose();     
    }//GEN-LAST:event_huongDanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrangChu tc = new TrangChu();
                tc.setVisible(true);
                tc.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton huongDanButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ngauNhienButton;
    private javax.swing.JButton nhapCungButton;
    private javax.swing.JButton nhapFileButton;
    private javax.swing.JLabel tieuDeLabel;
    // End of variables declaration//GEN-END:variables
}
